### ISSUE TITLE
Why not on Server? 

### ISSUE THREAD

**Issue by 7h1ru** [rnaby/tCableBilling#2]
Is there any special reason for not recommending to install it on a server? BTW Great work there. :)

**Comment by rnaby** [comment]
Hi,

First, thanks for the compliment. Actually, the applications wasn't ready that time to deploy on server cause there were some user management issue. Also the user role management isn't that mature yet. So, I thought deploying in server will cause some confusion. That's why I discouraged server deploying. But if you like it on server, go for it.

Regards,
Khan

**Comment by sachin0606** [comment]
Hi rnbay, 

the tool is really good. but wanted to know any method to two sync method with server and application in case developed any idea??

**Comment by rnaby** [comment]
Hi Sachin,

Thanks for the compliment. Actually, I'm not sure what you are talking about. Please express it more elaborately. ***And I think it would be better if you create another issue regarding your matter to discuss further.***

Regards,
Khan
